<h1 style="color:pink; text-align:center;">Name: Vaibhav Kumar</h1>
<h1 style="color:pink; text-align:center;">SAP ID: 590021603</h1>

<br><hr><br>

<h2 style="text-align:center;">Lab Experiments</h2>
<h2 style="text-align:center;">Data Analysis and Visualization</h2>

<br><hr><br>

<h2><b>Question: </b>Create numpy array to find sum of all elements in an array?</h2>
<h2><b>Code: </b></h2>

In [1]:
import numpy as np

array = np.array([7, 12, 9, 4, 11, 25, 15])
print("Array: ", array)
print("Sum of all elements: ", np.sum(array))

Array:  [ 7 12  9  4 11 25 15]
Sum of all elements:  83


<br><hr><br>

<h2><b>Question: </b>Create numpy array of (3, 3) dimension. Now find sum of all rows and columns individually. Also find 2<sup>nd</sup> maximum element in the array.</h2>
<h2><b>Code: </b></h2>

In [3]:
matrix_3x3 = np.array([
    [9, 12, 15],
    [7, 12, 9],
    [4, 11, 25]
])

SumOfRows = np.sum(matrix_3x3, axis=1)
SumOfColumns = np.sum(matrix_3x3, axis=0)
SecondMaximum = np.unique(matrix_3x3.flatten()) [-2]

print("3x3 Matrix ", matrix_3x3)
print("Sum of Rows: ", SumOfRows)
print("Sum of Columns: ", SumOfColumns)
print("Second Maximum element: ", SecondMaximum)

3x3 Matrix  [[ 9 12 15]
 [ 7 12  9]
 [ 4 11 25]]
Sum of Rows:  [36 28 40]
Sum of Columns:  [20 35 49]
Second Maximum element:  15


<br><hr><br>
<h2><b>Question: </b>Perform Matrix multiplication of any 2 n*n matrices.</h2>
<h2><b>Code: </b></h2>

In [5]:
MatrixA = np.array([
    [7, 12, 9],
    [11, 20, 25],
    [3, 9, 12]
])

MatrixB = np.array([
    [7, 12, 9],
    [11, 20, 25],
    [3, 9, 12]
])

productOfMatrix = MatrixA @ MatrixB

print("Matrix A: ", MatrixA)

print("Matrix B: ", MatrixB)

print("MatrixA x MatrixB", productOfMatrix)

Matrix A:  [[ 7 12  9]
 [11 20 25]
 [ 3  9 12]]
Matrix B:  [[ 7 12  9]
 [11 20 25]
 [ 3  9 12]]
MatrixA x MatrixB [[208 405 471]
 [372 757 899]
 [156 324 396]]


<br><hr><br>
<h2><b>Question: </b>Write a Pandas program to get the powers of an array values element-wise.</h2>
<h2>Code: </h2>

In [4]:
import pandas as pd

baseValue = pd.Series([0, 1, 2, 3, 4, 5, 6], name = "base")
powerValue = pd.Series([0, 1, 2, 3, 4, 5, 6], name = "power")
poweredValues = baseValue.pow(powerValue)

print("Base Values: ", baseValue)
print("Power Values: ", poweredValues)

print("Powers of an array values element-wise: ", poweredValues)

Base Values:  0    0
1    1
2    2
3    3
4    4
5    5
6    6
Name: base, dtype: int64
Power Values:  0        1
1        1
2        4
3       27
4      256
5     3125
6    46656
dtype: int64
Powers of an array values element-wise:  0        1
1        1
2        4
3       27
4      256
5     3125
6    46656
dtype: int64


<br><hr></br>
<h2><b>Question: </b>Write a pandas program to get the first 3 rows of a given Dataframe.</h2>
<h2><b>Code:</b></h2>

In [7]:
import numpy as np
import pandas as pd

examData = {
    "name": ["Anastasia", "Dima", "Katherine", "James", "Emily", "Michael", "Matthew", "Laura", "Kevin", "Jonas"],
    "score": [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    "attempts": [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    "qualify": ["yes", "no", "yes", "no", "no", "yes", "yes", "no", "no", "yes"],
}
labels = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]

examDataFrame = pd.DataFrame(examData, index=labels)

print("Complete DataFrame:")
print(examDataFrame)
print("First three rows:")
print(examDataFrame.head(3))

Complete DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
First three rows:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


<br><hr><br>